spring.application.name=bulela-medical-tracker

spring.datasource.url=jdbc:mariadb://localhost:3306/bulela_medical_tracker
spring.datasource.username=bulela_app
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
